# Generated by Django 4.0.6 on 2022-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
