# Generated by Django 4.0.6 on 2022-07-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_transaction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
