# Generated by Django 4.0.6 on 2022-07-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paid_transactions',
            new_name='paid_transactions_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pending_transactions',
            new_name='pending_transactions_id',
        ),
    ]
