# Generated by Django 4.0.6 on 2022-07-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processor',
            old_name='processor',
            new_name='name',
        ),
    ]
