# Generated by Django 4.0.6 on 2022-07-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_processor_processor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
